"""followers

Revision ID: 705c0baeace7
Revises: e830ca1e0899
Create Date: 2018-03-27 19:53:10.317147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705c0baeace7'
down_revision = 'e830ca1e0899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
